name 'grub'
maintainer 'Bloomberg L.P.'
maintainer_email 'acaiafa1@bloomberg.net'
description 'Configures grub'
long_description 'Configures grub'
version '0.2.0'

supports 'centos', '>= 6.4'
supports 'redhat', '>= 6.4'
supports 'ubuntu', '>= 12.04'
